### ISSUE TITLE
Bug in `resolve_project_path`

### ISSUE THREAD

**Issue by kenbeese** [kenbeese/DataProcessor#195]
`project_id`に`.` or `..`を指定するとやばい。

相対バスの解決が全体的に甘い.

```
resolve_project_path("hoge", False)
resolve_project_path(".", False)
resolve_project_path("..", False)
```

- カレントディレクトリにhogeディレクトリがある場合、一つ目をどうするか。
- 2つめと、3つめは`basket_name`で指定したとこからの相対パスになる

**Comment by termoshtt** [comment]
- `resolve_project_path("hoge", False)`のhogeはname
- 残り2つはpathとして認識する

**Comment by termoshtt** [comment]
nameでなくtagという名称を使用すべき（nameは既に存在する）
