### ISSUE TITLE
utilityの関数の名前を適切につける

### ISSUE THREAD

**Issue by xeno1991** [kenbeese/DataProcessor#204]
unitily.pyの内部の以下の関数について、名前を適切に付け直す

- path_expand
  - 絶対パスを返すのがわからない
- check_file
  - チェックして例外投げるだけじゃなくて絶対パスを返している
- check_directory
  - チェックして例外投げるだけじゃなくて絶対パスを返している
- get_directory
  - ディレクトリを作ることがわからない

**Comment by termoshtt** [comment]
- abspath
- file_abspath
- dir_abspath
- get_or_create_dir_abspath

最後のがつらい

**Comment by termoshtt** [comment]
- abspath
- check_file (確認のみ)
- check_dir (確認のみ)
- check_or_create_dir (なければ作る)
