### ISSUE TITLE
true/false → 1.0/0.0

### ISSUE THREAD

**Issue by xeno1991** [kenbeese/DataProcessor#219]
true/false in yaml becomes 1.0/0.0 on web interface.

I think it should be true/false as string, not floating number.

**Comment by termoshtt** [comment]
もう少し状況を詳しく教えてください。
web interfaceはコメントのこと？pipe呼ぶAPIのところ？

**Comment by xeno1991** [comment]
例えば、↓のようなyamlが
```yaml
chebyshev_span: true
...
```

![](https://i.gyazo.com/0df18c82c1f62cd46340558445f2e1be.png)

のようになります。true/falseのままなほうが良いかと。

**Comment by termoshtt** [comment]
これはYAMLの問題ではなくて、table作るときに一旦dataframeを経由しますが、そのさいにflaotかましてるのが原因ですね。

**Comment by termoshtt** [comment]
https://github.com/kenbeese/DataProcessor/blob/master/lib/dataprocessor/dataframe.py#L73
